### ISSUE TITLE
프록시 설정을 위한 URI 설계 변경 건

### ISSUE THREAD

**Issue by woo00oo** [woo00oo/goGetterProjectServer#43]
- 리엑트(3000)에서 프록시 설정을 위해 기존 Rest API URI 변경
- 기존 /api , /useapi, /admapi 수정 해야함
- 모든 시작 URI /api로 시작하고 비회원, 일반회원, 블랙회원, 관리자를 계층형으로 등급을 나눠야함

ex)
-  /api/admapi
-  /api/userapi
- /api/signup

**Comment by woo00oo** [comment]
쿠키 정책으로 인해 프록시 설정을 해줘야 합니다.

**Comment by kimyubi** [comment]
확인했습니다. 변경사항 반영하여 URI 변경하겠습니다 !

**Comment by woo00oo** [comment]
> 확인했습니다. 변경사항 반영하여 URI 수정하겠습니다!
> 
> api - 블랙리스트 회원 사용, 일반 회원 사용, 관리자 사용
> 
> userapi - 일반 회원 사용, 관리자 사용
> 
> admapi - 관리자
> 
> 기존의 블랙 회원은 /api로 시작했었는데 , 그러면 /api/api로 설계해야 하는 건가요?

블랙회원, 일반 회원 , 관리자 -> /api/g1
일반 회원, 관리자 -> /api/g2
관리자 -> /api/g3 

이런식으로 둬도 괜찮을 거 같은데 다른 크루님들은 어떻게 생각하시나요?~

**Comment by seoyoungsoo** [comment]
> > 확인했습니다. 변경사항 반영하여 URI 수정하겠습니다!
> > api - 블랙리스트 회원 사용, 일반 회원 사용, 관리자 사용
> > userapi - 일반 회원 사용, 관리자 사용
> > admapi - 관리자
> > 기존의 블랙 회원은 /api로 시작했었는데 , 그러면 /api/api로 설계해야 하는 건가요?
> 
> 블랙회원, 일반 회원 , 관리자 -> /api/g1
> 일반 회원, 관리자 -> /api/g2
> 관리자 -> /api/g3
> 
> 이런식으로 둬도 괜찮을 거 같은데 다른 크루님들은 어떻게 생각하시나요?~

**Comment by seoyoungsoo** [comment]
> > 확인했습니다. 변경사항 반영하여 URI 수정하겠습니다!
> > api - 블랙리스트 회원 사용, 일반 회원 사용, 관리자 사용
> > userapi - 일반 회원 사용, 관리자 사용
> > admapi - 관리자
> > 기존의 블랙 회원은 /api로 시작했었는데 , 그러면 /api/api로 설계해야 하는 건가요?
> 
> 블랙회원, 일반 회원 , 관리자 -> /api/g1
> 일반 회원, 관리자 -> /api/g2
> 관리자 -> /api/g3
> 
> 이런식으로 둬도 괜찮을 거 같은데 다른 크루님들은 어떻게 생각하시나요?~

좀 더 restful하게 외부에서 봤을 때도 이해할 수 있는 명칭이 필요할 것 같습니다
비회원 -> /api/~
일반 회원 -> /api/users/~
관리자 -> /api/admin/~
이런 식으로 하는게 어떨까요?

**Comment by woo00oo** [comment]
> > > 확인했습니다. 변경사항 반영하여 URI 수정하겠습니다!
> > > api - 블랙리스트 회원 사용, 일반 회원 사용, 관리자 사용
> > > userapi - 일반 회원 사용, 관리자 사용
> > > admapi - 관리자
> > > 기존의 블랙 회원은 /api로 시작했었는데 , 그러면 /api/api로 설계해야 하는 건가요?
> > 
> > 
> > 블랙회원, 일반 회원 , 관리자 -> /api/g1
> > 일반 회원, 관리자 -> /api/g2
> > 관리자 -> /api/g3
> > 이런식으로 둬도 괜찮을 거 같은데 다른 크루님들은 어떻게 생각하시나요?~
> 
> 좀 더 restful하게 외부에서 봤을 때도 이해할 수 있는 명칭이 필요할 것 같습니다
> 비회원 -> /api/~
> 일반 회원 -> /api/users/~
> 관리자 -> /api/admin/~
> 이런 식으로 하는게 어떨까요?

블랙 회원은 어떻게 둘까요??

**Comment by torvlf** [comment]
> > > > 확인했습니다. 변경사항 반영하여 URI 수정하겠습니다!
> > > > api - 블랙리스트 회원 사용, 일반 회원 사용, 관리자 사용
> > > > userapi - 일반 회원 사용, 관리자 사용
> > > > admapi - 관리자
> > > > 기존의 블랙 회원은 /api로 시작했었는데 , 그러면 /api/api로 설계해야 하는 건가요?
> > > 
> > > 
> > > 블랙회원, 일반 회원 , 관리자 -> /api/g1
> > > 일반 회원, 관리자 -> /api/g2
> > > 관리자 -> /api/g3
> > > 이런식으로 둬도 괜찮을 거 같은데 다른 크루님들은 어떻게 생각하시나요?~
> > 
> > 
> > 좀 더 restful하게 외부에서 봤을 때도 이해할 수 있는 명칭이 필요할 것 같습니다
> > 비회원 -> /api/~
> > 일반 회원 -> /api/users/~
> > 관리자 -> /api/admin/~
> > 이런 식으로 하는게 어떨까요?
> 
> 블랙 회원은 어떻게 둘까요??

블랙회원 -> /api/bkuser/~ 
이런식으로 하면 어떨까요?

**Comment by woo00oo** [comment]
> > > > > 확인했습니다. 변경사항 반영하여 URI 수정하겠습니다!
> > > > > api - 블랙리스트 회원 사용, 일반 회원 사용, 관리자 사용
> > > > > userapi - 일반 회원 사용, 관리자 사용
> > > > > admapi - 관리자
> > > > > 기존의 블랙 회원은 /api로 시작했었는데 , 그러면 /api/api로 설계해야 하는 건가요?
> > > > 
> > > > 
> > > > 블랙회원, 일반 회원 , 관리자 -> /api/g1
> > > > 일반 회원, 관리자 -> /api/g2
> > > > 관리자 -> /api/g3
> > > > 이런식으로 둬도 괜찮을 거 같은데 다른 크루님들은 어떻게 생각하시나요?~
> > > 
> > > 
> > > 좀 더 restful하게 외부에서 봤을 때도 이해할 수 있는 명칭이 필요할 것 같습니다
> > > 비회원 -> /api/~
> > > 일반 회원 -> /api/users/~
> > > 관리자 -> /api/admin/~
> > > 이런 식으로 하는게 어떨까요?
> > 
> > 
> > 블랙 회원은 어떻게 둘까요??
> 
> 블랙회원 -> /api/bkuser/~
> 이런식으로 하면 어떨까요?

오 좋은거 같습니다! 👍
