### ISSUE TITLE
공유 게시판 게시글 수정 및 삭제 API Refactoring

### ISSUE THREAD

**Issue by kimyubi** [woo00oo/goGetterProjectServer#66]
- 본인의 글이 아니면 수정 및 삭제 할 수 없도록 함.
- 사용자 정보 전체를 조회해오던 것에서 사용자의 아이디, 프로필 url만 조회해오도록 수정.
- 업데이트 변경사항 확인하는 코드 삭제
=> JPA에서 변경감지 기능을 제공하기 때문에 변경사항 확인 코드를 따로 작성할 필요가 없음.

**Comment by woo00oo** [comment]
업데이트 관련해서는 JPA 더티체킹에 대해서 알아보시면 좋을 거 같네요~

**Comment by kimyubi** [comment]
> 업데이트 관련해서는 JPA 더티체킹에 대해서 알아보시면 좋을 거 같네요~

넵 확인했습니다 ~
